# Generated by Django 4.0.4 on 2022-05-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.CharField(max_length=225)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
